{% set version = "0.8.3" %}

package:
  name: jaws
  version: {{ version }}

source:
  url: https://github.com/jaws/jaws/archive/{{ version }}.tar.gz
  sha256: a1a88035c1dc270636a97e56b99955e943f717383364d17328548813ee4e17fc

build:
  number: 1
  # script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - pandas
    - scipy
    - numpy >=1.15.2
    - requests
    - xarray
    - metpy >=0.10.0
  run:
    - python
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4
    - scipy
    - requests
    - metpy >=0.10.0

test:
  imports:
    - jaws
    - jaws.aaws2nc
    - jaws.gcnet2nc
    - jaws.imau2nc
    - jaws.promice2nc

about:
  home: https://github.com/jaws/jaws
  license: Apache, Version 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Justify idiosyncratic ASCII AWS formats into analyzable netCDF formats.'

extra:
  recipe-maintainers:
    - ajcse1
    - czender
