{% set version = "0.7.5" %}

package:
  name: jaws
  version: {{ version }}

source:
  url: https://github.com/jaws/jaws/archive/{{ version }}.tar.gz
  sha256: 15cdc750fc74e2161c0795d4a1c6c4f10519c7147be15263c447fd3240c09582

build:
  #noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pandas
    - scipy
    - numpy >=1.15.2
  run:
    - python
    - pandas
    - numpy >=1.15.2
    - xarray
    - pytz
    - netcdf4
    - matplotlib
    - netcdf4
    - scipy
    - requests

test:
  imports:
    - jaws
    - jaws.aaws2nc
    - jaws.gcnet2nc
    - jaws.imau2nc
    - jaws.promice2nc

about:
  home: https://github.com/jaws/jaws
  license: Apache, Version 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Justify idiosyncratic ASCII AWS formats into analyzable netCDF formats.'

extra:
  recipe-maintainers:
    - ajcse1
    - czender
