travis:
  secure:
    BINSTAR_TOKEN: K1LALIAJSz20KUOSiLmPLLYf22/5n+GCev4RhNeTC1TEGxHDzTmqriaeVLeGpY/RgsAPD6wOHbS+67qqS+5FsLZtXvtL4rtSJzkHricu6WmzIz/TNTsmdkDaLJqmh/YvkzfYZJpd/gKfYUjSgi4IDwcHUEi4IuC1298fIxZdGpxyCRu2TIMcsepDUp7oh4H8PvQc08dSjTFmf6bMcszz+8F9BlexFcDoOd7dn/S5GkiJlFuoKFrScxF0IdqcY1Mrn4ji68wlbPK7CTZBhQ5DCMHWyaHJ5fAK3eCkqQ7VOlMP4p/ZxzVofQH0B83owbwt0Eo8LmsLvtTMDodM93MUpbrZP7Ik7Ao83njLbn0gzFRVbnlppcE40K7jSEbxGgcow8B4FiPmx+yHlF1tSqeUx/4TNaaun6VpT1fbDso9JyfA23J3Qe4JUD6ZKsH3r/H7OkgL09dmY/c6p+pVjua+tM2hkdUmd+gq/bSLMR/0biKvwlltSr7l2x1lnmGRa+Db9yZ6O2BquZphzPuSkys74BFPnpULhU0wT2sJ6s3AAJAccXdpwBkqNnsQB2PAKeXy6ijBkUZcAQXd5lI4LEOFyVpOLdH+8stA+kf6VyWQeyfy6JsPDSgrAtKScG9kzEVRynj8AWhFvAbLAUANznHn7Jop/sgaiM+T7p2bb/nr3m4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
